# Generated by Django 4.1.7 on 2023-04-27 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0004_remove_additem_tax_additem_interstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150, null=True)),
                ('vendor_display_name', models.CharField(max_length=150, null=True)),
                ('vendor_email', models.CharField(max_length=250, null=True)),
                ('vendor_wphone', models.CharField(max_length=50, null=True)),
                ('vendor_mphone', models.CharField(max_length=50, null=True)),
                ('skype_number', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('website', models.CharField(max_length=250, null=True)),
                ('gst_treatment', models.CharField(max_length=100, null=True)),
                ('gst_number', models.CharField(max_length=50, null=True)),
                ('pan_number', models.CharField(max_length=50, null=True)),
                ('source_supply', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('opening_bal', models.CharField(max_length=100, null=True)),
                ('payment_terms', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
