# Generated by Django 4.2 on 2023-04-19 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0005_company_details_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=255)),
                ('Name', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('s_desc', models.TextField(max_length=255)),
                ('p_desc', models.TextField(max_length=255)),
                ('creat', models.CharField(max_length=255)),
                ('s_price', models.CharField(max_length=255)),
                ('p_price', models.TextField(max_length=255)),
                ('satus', models.TextField(default='active')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_name', models.TextField(max_length=255)),
                ('Acount_code', models.TextField(max_length=255)),
                ('Account_desc', models.TextField(max_length=255)),
                ('Account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_name', models.TextField(max_length=255)),
                ('Acount_code', models.TextField(max_length=255)),
                ('Account_desc', models.TextField(max_length=255)),
                ('Account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='additem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.purchase'),
        ),
        migrations.AddField(
            model_name='additem',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.sales'),
        ),
        migrations.AddField(
            model_name='additem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.unit'),
        ),
        migrations.AddField(
            model_name='additem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
