# Generated by Django 4.1.7 on 2023-04-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='gst_treatment',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='opening_bal',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='source_supply',
        ),
    ]
