# Generated by Django 4.2 on 2023-04-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_account_additem_unit_sales_purchase_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Account_type',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Account_type',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
