# Generated by Django 4.1.7 on 2023-04-28 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0009_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('vendor_display_name', models.CharField(max_length=150)),
                ('vendor_email', models.CharField(max_length=250)),
                ('vendor_wphone', models.CharField(max_length=50)),
                ('vendor_mphone', models.CharField(max_length=50)),
                ('skype_number', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
                ('gst_treatment', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=50, null=True)),
                ('pan_number', models.CharField(max_length=50, null=True)),
                ('source_supply', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('opening_bal', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
