# Generated by Django 4.1.7 on 2023-05-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_doc_upload_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor',
        ),
    ]
