# Generated by Django 4.1.7 on 2023-05-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_contact_person_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_person_table',
        ),
    ]
