# Generated by Django 4.1.7 on 2023-05-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0021_remove_doc_upload_table_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_table',
        ),
    ]
