# Generated by Django 4.1.7 on 2023-05-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_mail_table_doc_upload_table_comments_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_upload_table1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doc_upload_table1',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='mail_table1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mail_table1',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='comments_table1',
        ),
        migrations.DeleteModel(
            name='doc_upload_table1',
        ),
        migrations.DeleteModel(
            name='mail_table1',
        ),
    ]
