# Generated by Django 4.1.7 on 2023-05-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_remarks_table1_contact_person_table1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks_table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remarks_table',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='contact_person_table',
        ),
        migrations.DeleteModel(
            name='remarks_table',
        ),
    ]
