# Generated by Django 4.1.7 on 2023-05-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0027_remove_remarks_table_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_table1',
        ),
    ]
