# Generated by Django 4.1.7 on 2023-05-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0029_remarks_table_contact_person_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks_table1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remarks_table1',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='contact_person_table1',
        ),
        migrations.DeleteModel(
            name='remarks_table1',
        ),
    ]
